### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by asishm** [nagracks/reddit_get_top_images#12]
`python get_top_images.py -s motivation -p m` throws an 

```
OSError: [Errno 22] Invalid argument: '~\reddit_pics\motivation_jpg?1.jpeg'
```

Going to need some sort of validation for the file name.

**Comment by nagracks** [comment]
It works fine on linux. `motivation_jpg?1.jpeg` is saved. It might only be problem on Windows. I think Windows don't  like `?` in names.

**Comment by asishm** [comment]
Yeah shows up as error in Windows. Some sort of function to replace all those special  characters by `''` the null string?

**Comment by Lvl4Sword** [comment]
You could always replace ? with a dash ( - )

**Comment by nagracks** [comment]
Yeah right we could replace it with 'x' then '-'. What you say?

**Comment by asishm** [comment]
The url that causes this issue is 
`http://i.imgur.com/oYPSVUE.jpg?1`

If there is another post in the subreddit with another image like `http://i.imgur.com/5sXn55M.jpg?1`
this will also lead to the same file name being generated as the one above. which will lead to the image not getting downloaded since the script will say the file already exists.

**Comment by nagracks** [comment]
No. See this in `download_it(url, tir)` how we make random filename

```
    # Splits to get some characters from in-url filename
    # This helps to make random filename
    url_chars = url.split('/')[-1][-10:]
    # Make random filename with subreddit name and random chars
    file_name = "{name}_{chars}".format(name=tir.subreddit, chars=url_chars)
```

**Comment by Lvl4Sword** [comment]
look like url_chars should instead be something like this then:

> url.split('/')[1].rstrip('?123456789')

the [-10:] is useless because you have no idea how many characters the filename will be.
let me know if that fixes it :)

**Comment by nagracks** [comment]
Right, it should work. I'll do it when I have the time.

**Comment by asishm** [comment]
@nagracks that isn't randomizing the file name at all, it just takes the subreddit name and adds the last 10 characters of the url separated by _. If the above two images (`http://i.imgur.com/oYPSVUE.jpg?1` and `http://i.imgur.com/5sXn55M.jpg?1` ) were both in the list of urls received, then both would have the same `file_name`. 

@Lvl4Sword I think you meant  `url.split('/')[-1].rstrip('?123456789')`. This won't work since the `url` is of the format `{link}.{ext}` The illegal characters are in the `link` section. So `rstrip` wouldn't remove them.
What I'd do is define `illegal_chars = '/?<>\\:*|"'`

```
url_chars = url.split('/')[-1]
for char in illegal_chars:
    url_chars = url_chars.replace(char, '')
```

and then finally add this:

```
if len(file_name) > 255:
    file_name = file_name[-255:]
```

since Windows complains of file names having > 255 characters.
I'll send in a pull request if we agree on this

**Comment by nagracks** [comment]
> that isn't randomizing the file name at all, it just takes the subreddit name and adds the last 10 characters of the url separated by _.

Why cannot this be called randomizing?

>  If the above two images (http://i.imgur.com/oYPSVUE.jpg?1 and http://i.imgur.com/5sXn55M.jpg?1 ) were both in the list of urls received, then both would have the same file_name.

How would they be on same file_name? the name would be `subname_SVUE.jpg?1` and `subname_n55M.jpg?1`. `?1` at the end is bug this needs fix.

Well you can send PR I'll see.

**Comment by asishm** [comment]
@nagracks the way the url function works, it will add `.jpeg` to any link that either
- doesn't end in a `.format` or 
- is an imgur link without `/a/` or `/gallery/`

Since these two links are neither, the url that the function returns is `http://i.imgur.com/oYPSVUE.jpg?1.jpeg` and `http://i.imgur.com/5sXn55M.jpg?1.jpeg` whose last 10 characters are both `jpg1?`.jpeg`

As to why it is not randomizing, it's because it's purely deterministic, it can be called name mangling, but not randomizing. Randomizing is when there's a certain uncertainty in stuff.
