### ISSUE TITLE
How to get the caption?

### ISSUE THREAD

**Issue by DerLomo** [nagracks/reddit_get_top_images#27]
It would be extremly beneficial to geet along the photos cpations/tittles of those.
Is there some way to get them?
I am interesting of for example only getting 1 photo per day, how I could get the tittle via script?

**Comment by bbkane** [comment]
I wrote a CLI that incorporates the subreddit name, the the title, and part of the link into the downloaded images at https://github.com/bbkane/grabbit .

Here are some of the files I've downloaded with it:

```
villageporn_Village_of_Miravet,_along_the_Ebro_river,_Spain_[OC]_hohxjbxvtav61.jpg
wallpapers_Study_Room_[3840x2160]_Zi9lTse.jpg
imaginaryinteriors_Shrine_of_Hephaestus_by_Jan_Drenovec_jan-drenovec-shrineofhephaestus-full.jpg
```

Would `grabbit` do what you need it to?
