### ISSUE TITLE
Changing download location?

### ISSUE THREAD

**Issue by narimiran** [nagracks/reddit_get_top_images#6]
Would you be interested in adding an option for specifying a download location?

For example, it could be either home directory (current setting) or current working directory (directory where's .py file - `os.getcwd()`). 
Or maybe user could specify a path to a directory where he wants images to be saved?

**Comment by nagracks** [comment]
Yeah I am interested and I also want to improve the design of API

**Comment by narimiran** [comment]
>  I also want to improve the design of API

I have an idea to change how 'get_from_*' methods work. They are all very similar (lots of repeated code), so I would replace them with one method.  
I'll create separate branch for this so you can see what I mean.

**Comment by narimiran** [comment]
See [here](https://github.com/narimiran/reddit_get_top_images/blob/get_top/get_top_images.py) the refactored version. Let me know what do you think. (I didn't update the readme, just the .py file)

**Comment by nagracks** [comment]
Yes this is amazingly refactored. Send pull request

**Comment by nagracks** [comment]
I am learning alot from you

**Comment by narimiran** [comment]
> I am learning alot from you

Thank you! It's really nice to hear that :)  
Btw, I never used argparse before, so I'm learning something from you, too ;)

**Comment by nagracks** [comment]
I am going to refactor download_it function

**Comment by narimiran** [comment]
Ok, I won't do anything new today, I'm waiting for your new commits. (Btw, I'll leave changing readme to you too ;))

**Comment by nagracks** [comment]
Yeah okay 👍
